name: Deploy Hugo Catalog

on:
  push:
    branches:
      - main # Set a branch to deploy
  schedule:
   - cron: "30 14 * * *"
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Hugo restore setup
        uses: peaceiris/actions-hugo@v2.6.0
        if: github.event.schedule == '30 14 * * 3'
        with:
          hugo-version: "latest"
          extended: true
          ref: restore

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.6.0
        if: github.event.schedule != '30 14 * * 3'
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify --baseURL ${{secrets.BASE_URL}}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
